version: "3.8"

services:

  knpki-kms-database:
    container_name: knpki-kms-database
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin_root_password_indonesiakeluargaperlindungannasionalkoalisi
      MYSQL_DATABASE: knpki_kms
      MYSQL_USER: knpkid
      MYSQL_PASSWORD: indonesiakeluargaperlindungannasionalkoalisi
    volumes:
      - "./backup/knpki_kms_backup.sql:/docker-entrypoint-initdb.d/init.sql"

  knpki-kms-redis:
    container_name: knpki-kms-redis
    image: redis:7.2.4
    command: redis-server
    ports:
      - "6379:6379"

  knpki-kms:
    container_name: knpki-kms
    build:
      context: .
      dockerfile: Dockerfile
    image: mhmmdnaufal/knpki-kms:1.0.0
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: knpkid
      DATABASE_PASSWORD: indonesiakeluargaperlindungannasionalkoalisi
      DATABASE_URL: jdbc:mysql://knpki-kms-database:3306/knpki_kms
      APP_PORT: 8080
    restart: on-failure
    depends_on:
      - knpki-kms-database

