version: "3.8"

services:

  knpki-kms-database:
    container_name: knpki-kms-database
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin_root_password_indonesiakeluargaperlindungannasionalkoalisi
      MYSQL_DATABASE: knpki_kms
      MYSQL_USER: knpkid
      MYSQL_PASSWORD: indonesiakeluargaperlindungannasionalkoalisi
    volumes:
      - "knpki-kms-data:/var/lib/mysql"

  knpki-kms:
    container_name: knpki-kms
    image: mhmmdnaufal/knpki-kms:1.2.0
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: knpkid
      DATABASE_PASSWORD: indonesiakeluargaperlindungannasionalkoalisi
      DATABASE_URL: jdbc:mysql://knpki-kms-database:3306/knpki_kms
      APP_PORT: 8080
    restart: on-failure
    depends_on:
      - knpki-kms-database
    volumes:
      - "knpki-kms-image:/application/image"

volumes:
  knpki-kms-image:
    name: knpki-kms-image
  knpki-kms-data:
    name: knpki-kms-data

