spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/knpki_kms
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

app:
  jwt:
    secret: SkripsiKmsKnpkiIbuEuisSunartiPakIrmanHermadiMuhammadNaufalATiarIswantiSkripsiKmsKnpkiIbuEuisSunartiPakIrmanHermadiMuhammadNaufalATiarIswanti
    expirationDays: 7
