spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/knpki_kms}
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    open-in-view: true

  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      timeout: 5s
      connect-timeout: 10s
      database: 0

  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: "cache:"
      cache-null-values: false
      enable-statistics: false
      time-to-live: 86400s # 1 day

app:
  jwt:
    secret: SkripsiKmsKnpkiIbuEuisSunartiPakIrmanHermadiMuhammadNaufalATiarIswantiSkripsiKmsKnpkiIbuEuisSunartiPakIrmanHermadiMuhammadNaufalATiarIswanti
    expirationMs: 86400000
