spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/knpki_kms}
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    open-in-view: true

app:
  jwt:
    secret: SkripsiKmsKnpkiIbuEuisSunartiPakIrmanHermadiMuhammadNaufalATiarIswantiSkripsiKmsKnpkiIbuEuisSunartiPakIrmanHermadiMuhammadNaufalATiarIswanti
    expirationMs: 86400000
